# Generated by Django 3.2.9 on 2021-11-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='admin',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
